apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-gateway
  template:
    metadata:
      labels:
        app: restaurant-gateway
    spec:
      containers:
        - name: restaurant-gateway
          image: basilamed/restaurantgateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: Urls__Users
              value: "http://restaurant-rest-service:8080"
            - name: Urls__Items
              value: "http://restaurant-go-service:8000"
            - name: Urls__Orders
              value: "http://restaurant-async-service:8080"
      initContainers:
        - name: check-restaurant-rest-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://restaurant-rest-service:8080/healthz; do echo waiting for restaurant-rest-service; sleep 2; done;']
        - name: check-restaurant-go-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://restaurant-go-service:8000/healthz; do echo waiting for restaurant-go-service; sleep 2; done;']
        - name: check-restaurant-async-service
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -qO- http://restaurant-async-service:8080/healthz; do echo waiting for restaurant-async-service; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-gateway-service
spec:
  type: NodePort
  selector:
    app: restaurant-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080