apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-rest
  template:
    metadata:
      labels:
        app: restaurant-rest
    spec:
      containers:
        - name: restaurant-rest
          image: basilamed/restaurantrest:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sql-server-service,1433;User ID=sa;Password=Basila123.;Pooling=False;Encrypt=True;Trust Server Certificate=True"
      initContainers:
        - name: check-sql-server
          image: busybox:1.36.1
          command: ['sh', '-c', 'until nc -z -v -w30 sql-server-service 1433; do echo waiting for sql-server-service; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-rest-service
spec:
  type: NodePort
  selector:
    app: restaurant-rest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80